"""
FastAPI recommendation endpoints.

Endpoints:
    GET /api/v1/recommendations/{customer_id}
    GET /api/v1/recommendations/{customer_id}/history
    GET /api/v1/recommendations/{customer_id}/saved
    GET /api/v1/recommendations/metadata

The endpoint layer delegates recommendation logic to
RecommendationService.
"""

from __future__ import annotations

from typing import Any

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel, Field

from backend.services.recommendation_service import (
    RecommendationService,
)


router = APIRouter()


# ---------------------------------------------------------------------------
# RESPONSE SCHEMAS
# ---------------------------------------------------------------------------

class RecommendationItem(BaseModel):
    """One recommended product."""

    product_id: str
    rank: int = Field(
        ...,
        ge=1,
    )
    score: float | None = None
    method: str | None = None
    category: str | None = None


class RecommendationResponse(BaseModel):
    """Personalized recommendation response."""

    customer_id: str
    recommendations: list[RecommendationItem]
    count: int


class CustomerHistoryResponse(BaseModel):
    """Customer purchase-history response."""

    customer_id: str
    purchased_products: list[str]
    count: int


# ---------------------------------------------------------------------------
# ENDPOINTS
# ---------------------------------------------------------------------------

@router.get(
    "/{customer_id}",
    response_model=RecommendationResponse,
    summary="Get personalized product recommendations",
)
def get_recommendations(
    customer_id: str,
    k: int = Query(
        default=10,
        ge=1,
        le=50,
        description="Number of products to recommend.",
    ),
) -> RecommendationResponse:
    """
    Generate personalized recommendations for a customer.

    If the customer has no known purchase history, the service uses the
    popularity baseline as a cold-start fallback.
    """
    try:
        recommendations = (
            RecommendationService.recommend(
                customer_id=customer_id,
                k=k,
            )
        )

        return RecommendationResponse(
            customer_id=customer_id,
            recommendations=[
                RecommendationItem(**item)
                for item in recommendations
            ],
            count=len(recommendations),
        )

    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=503,
            detail=str(exc),
        ) from exc

    except ValueError as exc:
        raise HTTPException(
            status_code=422,
            detail=str(exc),
        ) from exc

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail="Recommendation service failed.",
        ) from exc


@router.get(
    "/{customer_id}/saved",
    response_model=RecommendationResponse,
    summary="Get precomputed recommendations",
)
def get_saved_recommendations(
    customer_id: str,
    k: int = Query(
        default=10,
        ge=1,
        le=50,
        description="Number of saved recommendations to return.",
    ),
) -> RecommendationResponse:
    """
    Return recommendations previously generated by notebook 06.

    This endpoint is useful when the dashboard should read precomputed
    recommendations instead of generating them on every request.
    """
    try:
        recommendations = (
            RecommendationService.get_saved_recommendations(
                customer_id=customer_id,
                k=k,
            )
        )

        return RecommendationResponse(
            customer_id=customer_id,
            recommendations=[
                RecommendationItem(**item)
                for item in recommendations
            ],
            count=len(recommendations),
        )

    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=503,
            detail=str(exc),
        ) from exc

    except ValueError as exc:
        raise HTTPException(
            status_code=422,
            detail=str(exc),
        ) from exc

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail="Saved recommendation service failed.",
        ) from exc


@router.get(
    "/{customer_id}/history",
    response_model=CustomerHistoryResponse,
    summary="Get customer purchase history",
)
def get_customer_history(
    customer_id: str,
) -> CustomerHistoryResponse:
    """Return the products previously purchased by a customer."""
    try:
        history = (
            RecommendationService.get_customer_history(
                customer_id=customer_id,
            )
        )

        return CustomerHistoryResponse(
            customer_id=customer_id,
            purchased_products=history,
            count=len(history),
        )

    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=503,
            detail=str(exc),
        ) from exc

    except ValueError as exc:
        raise HTTPException(
            status_code=422,
            detail=str(exc),
        ) from exc

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail="Customer history service failed.",
        ) from exc


@router.get(
    "/metadata",
    summary="Get recommendation artifact metadata",
)
def recommendation_metadata() -> dict[str, Any]:
    """Return non-sensitive metadata about the recommendation system."""
    try:
        return RecommendationService.metadata()

    except FileNotFoundError as exc:
        raise HTTPException(
            status_code=503,
            detail=str(exc),
        ) from exc

    except Exception as exc:
        raise HTTPException(
            status_code=500,
            detail="Unable to load recommendation metadata.",
        ) from exc
