"""
Streamlit product recommendations page.

Features:
- Enter a customer ID.
- Load personalized recommendations from FastAPI.
- Compare live/generated recommendations with saved recommendations.
- Show the customer's purchase history.
- Highlight cold-start behavior when no history is available.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st

from api_client import (
    APIClientError,
    api_client,
)


st.set_page_config(
    page_title="Recommendations | E-Commerce Intelligence",
    page_icon="🛍️",
    layout="wide",
)


# ---------------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------------

@st.cache_data(ttl=60)
def load_recommendations(
    customer_id: str,
    k: int,
) -> dict:
    """Load generated recommendations."""
    return api_client.recommendations(
        customer_id,
        k=k,
    )


@st.cache_data(ttl=60)
def load_saved_recommendations(
    customer_id: str,
    k: int,
) -> dict:
    """Load precomputed recommendations."""
    return api_client.saved_recommendations(
        customer_id,
        k=k,
    )


@st.cache_data(ttl=60)
def load_history(
    customer_id: str,
) -> dict:
    """Load customer purchase history."""
    return api_client.customer_history(
        customer_id
    )


@st.cache_data(ttl=300)
def load_metadata() -> dict:
    """Load recommender metadata."""
    return api_client.recommendation_metadata()


# ---------------------------------------------------------------------------
# HEADER
# ---------------------------------------------------------------------------

st.title("🛍️ Product Recommendations")

st.markdown(
    """
    Discover products that are most relevant to an individual customer
    using the recommendation engine exposed by FastAPI.
    """
)

st.info(
    "Recommendations are generated by the backend recommendation service. "
    "The Streamlit frontend only presents the ranked results."
)


# ---------------------------------------------------------------------------
# SIDEBAR CONTROLS
# ---------------------------------------------------------------------------

with st.sidebar:
    st.subheader("Recommendation Controls")

    customer_id = st.text_input(
        "Customer Unique ID",
        value=st.session_state.get(
            "selected_customer_id",
            "",
        ) or "",
        placeholder="Enter customer_unique_id",
    )

    recommendation_count = st.slider(
        "Number of recommendations",
        min_value=3,
        max_value=20,
        value=10,
    )

    source = st.radio(
        "Recommendation Source",
        options=[
            "Generated",
            "Precomputed",
        ],
        index=0,
    )

    load_button = st.button(
        "Get Recommendations",
        type="primary",
        use_container_width=True,
    )


# ---------------------------------------------------------------------------
# INPUT VALIDATION
# ---------------------------------------------------------------------------

if load_button:
    if not customer_id.strip():
        st.warning(
            "Please enter a customer ID."
        )
        st.stop()

    st.session_state.selected_customer_id = (
        customer_id.strip()
    )

selected_customer = st.session_state.get(
    "selected_customer_id"
)

if not selected_customer:
    st.info(
        "Enter a customer ID in the sidebar to generate recommendations."
    )
    st.stop()


# ---------------------------------------------------------------------------
# LOAD RECOMMENDATIONS
# ---------------------------------------------------------------------------

try:
    with st.spinner(
        "Loading recommendations..."
    ):
        if source == "Generated":
            recommendation_response = (
                load_recommendations(
                    selected_customer,
                    recommendation_count,
                )
            )
        else:
            recommendation_response = (
                load_saved_recommendations(
                    selected_customer,
                    recommendation_count,
                )
            )

        history_response = load_history(
            selected_customer
        )

except APIClientError as exc:
    st.error(
        "Unable to load recommendation data."
    )
    st.code(str(exc))
    st.stop()


# ---------------------------------------------------------------------------
# CUSTOMER CONTEXT
# ---------------------------------------------------------------------------

st.subheader(
    f"Recommendations for {selected_customer}"
)

purchased_products = history_response.get(
    "purchased_products",
    []
)

recommendations = recommendation_response.get(
    "recommendations",
    []
)

context_col1, context_col2, context_col3 = st.columns(3)

with context_col1:
    st.metric(
        "Previous Products",
        f"{len(purchased_products):,}",
    )

with context_col2:
    st.metric(
        "Recommendations",
        f"{len(recommendations):,}",
    )

with context_col3:
    st.metric(
        "Source",
        source,
    )


# ---------------------------------------------------------------------------
# COLD START
# ---------------------------------------------------------------------------

if not purchased_products:
    st.warning(
        """
        This customer has no known purchase history in the recommendation
        data. The backend may therefore use its popularity/cold-start
        fallback instead of personalized purchase-history similarity.
        """
    )


# ---------------------------------------------------------------------------
# RECOMMENDATION TABLE
# ---------------------------------------------------------------------------

st.subheader("Ranked Products")

if not recommendations:
    st.info(
        "No recommendations were returned for this customer."
    )
else:
    recommendation_df = pd.DataFrame(
        recommendations
    )

    # Normalize the common recommendation schema.
    display_columns = [
        "rank",
        "product_id",
        "score",
        "method",
        "category",
    ]

    available_columns = [
        column
        for column in display_columns
        if column in recommendation_df.columns
    ]

    display_df = recommendation_df[
        available_columns
    ].copy()

    if "rank" in display_df.columns:
        display_df["rank"] = pd.to_numeric(
            display_df["rank"],
            errors="coerce",
        )

    if "score" in display_df.columns:
        display_df["score"] = pd.to_numeric(
            display_df["score"],
            errors="coerce",
        ).round(4)

    st.dataframe(
        display_df,
        use_container_width=True,
        hide_index=True,
    )


# ---------------------------------------------------------------------------
# RECOMMENDATION SCORE CHART
# ---------------------------------------------------------------------------

if recommendations:
    score_df = pd.DataFrame(
        recommendations
    )

    if {
        "product_id",
        "score",
    }.issubset(score_df.columns):
        score_df["score"] = pd.to_numeric(
            score_df["score"],
            errors="coerce",
        )

        score_df = score_df.dropna(
            subset=["score"]
        )

        if not score_df.empty:
            score_df["product_label"] = (
                score_df["product_id"]
                .astype(str)
            )

            score_df = score_df.sort_values(
                "score",
                ascending=True,
            )

            import plotly.express as px

            fig = px.bar(
                score_df,
                x="score",
                y="product_label",
                orientation="h",
                labels={
                    "score": "Recommendation Score",
                    "product_label": "Product",
                },
            )

            fig.update_layout(
                height=max(
                    350,
                    45 * len(score_df),
                ),
                margin=dict(
                    l=20,
                    r=20,
                    t=30,
                    b=20,
                ),
            )

            st.subheader("Recommendation Strength")

            st.plotly_chart(
                fig,
                use_container_width=True,
            )


# ---------------------------------------------------------------------------
# PURCHASE HISTORY
# ---------------------------------------------------------------------------

st.subheader("🛒 Purchased Products")

if not purchased_products:
    st.info(
        "No purchase history is available."
    )
else:
    history_df = pd.DataFrame(
        {
            "Product ID": purchased_products
        }
    )

    st.dataframe(
        history_df,
        use_container_width=True,
        hide_index=True,
    )


# ---------------------------------------------------------------------------
# RECOMMENDER METADATA
# ---------------------------------------------------------------------------

with st.expander("Recommendation System Metadata"):
    try:
        metadata = load_metadata()
        st.json(metadata)
    except APIClientError as exc:
        st.warning(
            "Recommendation metadata is unavailable."
        )
        st.caption(str(exc))


# ---------------------------------------------------------------------------
# RAW RESPONSE
# ---------------------------------------------------------------------------

with st.expander("Raw Recommendation API Response"):
    st.json(recommendation_response)
