"""
Streamlit Groq AI Insights page.

Features:
- Check AI service availability.
- Generate an executive portfolio report.
- Generate a customer-level AI insight.
- Present AI output as business-oriented recommendations.

The LLM receives trusted analytical context from the FastAPI backend.
The Streamlit frontend does not call Groq directly.
"""

from __future__ import annotations

import streamlit as st

from api_client import (
    APIClientError,
    api_client,
)

st.set_page_config(
    page_title="AI Insights | E-Commerce Intelligence",
    page_icon="🤖",
    layout="wide",
)


# ---------------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------------

@st.cache_data(ttl=120)
def load_ai_status() -> dict:
    """Load Groq service status."""
    return api_client.ai_status()


def load_portfolio_report() -> dict:
    """Generate an executive AI report."""
    return api_client.ai_portfolio_report()


def load_customer_insight(
    customer_id: str,
) -> dict:
    """Generate a customer-level AI insight."""
    return api_client.ai_customer_insight(
        customer_id
    )


def extract_text(
    response: dict,
) -> str | None:
    """
    Extract common text fields from the AI service response.

    The backend remains the source of truth; this helper only makes the UI
    tolerant of small response-schema differences.
    """
    for key in [
        "report",
        "insight",
        "content",
        "response",
        "message",
        "text",
    ]:
        value = response.get(key)

        if isinstance(
            value,
            str,
        ) and value.strip():
            return value.strip()

    return None


# ---------------------------------------------------------------------------
# HEADER
# ---------------------------------------------------------------------------

st.title("🤖 AI Business Insights")

st.markdown(
    """
    Use Groq-powered natural-language analysis to interpret the trusted
    customer, CLV, segmentation, and retention outputs produced by the
    analytical backend.
    """
)

st.info(
    "AI Insights are generated by the FastAPI backend. "
    "The frontend never sends raw database credentials or calls Groq directly."
)


# ---------------------------------------------------------------------------
# AI SERVICE STATUS
# ---------------------------------------------------------------------------

st.subheader("AI Service Status")

try:
    status = load_ai_status()

    status_value = str(
        status.get(
            "status",
            status.get(
                "available",
                "unknown",
            ),
        )
    )

    status_col1, status_col2, status_col3 = st.columns(3)

    with status_col1:
        if status_value.lower() in {
            "ready",
            "available",
            "healthy",
            "true",
        }:
            st.success(
                "AI service available"
            )
        else:
            st.warning(
                f"AI status: {status_value}"
            )

    with status_col2:
        model = status.get(
            "model",
            status.get(
                "model_name",
                "Configured backend model",
            ),
        )

        st.metric(
            "Model",
            str(model),
        )

    with status_col3:
        provider = status.get(
            "provider",
            "Groq",
        )

        st.metric(
            "Provider",
            str(provider),
        )

except APIClientError as exc:
    st.error(
        "Unable to check AI service status."
    )
    st.code(str(exc))


# ---------------------------------------------------------------------------
# EXECUTIVE PORTFOLIO REPORT
# ---------------------------------------------------------------------------

st.divider()

st.subheader("📋 Executive Portfolio Report")

st.markdown(
    """
    Generate a concise business report based on the portfolio analytics
    already calculated by the backend.
    """
)

if st.button(
    "🤖 Generate Executive Report",
    type="primary",
    use_container_width=True,
):
    with st.spinner(
        "Generating executive AI report..."
    ):
        try:
            report_response = (
                load_portfolio_report()
            )

        except APIClientError as exc:
            st.error(
                "Unable to generate the AI report."
            )
            st.code(str(exc))
            report_response = None

    if report_response:
        report_text = extract_text(
            report_response
        )

        if report_text:
            st.markdown(
                report_text
            )
        else:
            st.warning(
                "The backend returned an AI response without a recognized "
                "text field."
            )
            st.json(report_response)

        with st.expander(
            "Raw AI Report Response"
        ):
            st.json(report_response)


# ---------------------------------------------------------------------------
# CUSTOMER AI INSIGHT
# ---------------------------------------------------------------------------

st.divider()

st.subheader("👤 Customer-Level AI Insight")

st.markdown(
    """
    Enter a customer ID to generate a natural-language interpretation of
    that customer's analytical profile.
    """
)

customer_id = st.text_input(
    "Customer Unique ID",
    value=st.session_state.get(
        "selected_customer_id",
        "",
    ) or "",
    placeholder="Enter customer_unique_id",
)

if st.button(
    "Generate Customer Insight",
    type="primary",
):
    if not customer_id.strip():
        st.warning(
            "Please enter a customer ID."
        )
    else:
        st.session_state.selected_customer_id = (
            customer_id.strip()
        )

        with st.spinner(
            "Generating customer insight..."
        ):
            try:
                insight_response = (
                    load_customer_insight(
                        st.session_state.selected_customer_id
                    )
                )

            except APIClientError as exc:
                st.error(
                    "Unable to generate customer insight."
                )
                st.code(str(exc))
                insight_response = None

        if insight_response:
            insight_text = extract_text(
                insight_response
            )

            if insight_text:
                st.markdown(
                    insight_text
                )
            else:
                st.warning(
                    "The backend returned a response without a recognized "
                    "AI text field."
                )
                st.json(insight_response)

            with st.expander(
                "Raw Customer AI Response"
            ):
                st.json(insight_response)


# ---------------------------------------------------------------------------
# RESPONSIBLE AI NOTE
# ---------------------------------------------------------------------------

st.divider()

with st.expander("AI Interpretation & Usage Notes"):
    st.markdown(
        """
        **How this feature is designed**

        1. Analytical services calculate the underlying customer metrics.
        2. FastAPI assembles trusted business context.
        3. The Groq service converts that context into natural-language
           business insights.
        4. Streamlit presents the resulting explanation.

        **Important**

        AI-generated recommendations should support business decisions,
        not replace validation of the underlying analytical metrics.
        """
    )
